spring.application.name=recipeforge-backend

spring.datasource.url=jdbc:mysql://awseb-e-dwgvpk3ewt-stack-awsebrdsdatabase-kcsnmtkvdadt.cnkas86kecus.us-east-2.rds.amazonaws.com/recipeforge?serverTimezone=America/Chicago

spring.datasource.username=admin
spring.datasource.password=guxveb-Wydxak-wuzfu2

spring.jpa.hibernate.ddl-auto=validate

spring.security.user.name=user
spring.security.user.password=${DEV_LOGIN_PASSWORD}